# Supported OpenAI models as of 2025-02-22
# Source: https://platform.openai.com/docs/models
model_names = [
    "gpt-4o",
    "chatgpt-4o-latest",
    "gpt-4o-mini",
    "o1",
    "o1-mini",
    "o3-mini",
    "o1-preview",
    "gpt-4o-realtime-preview",
    "gpt-4o-mini-realtime-preview",
    "gpt-4o-audio-preview",
    "gpt-4-turbo",
    "gpt-4-turbo-preview",
    "gpt-4",
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-0125",
    "gpt-3.5-turbo-1106",
    "gpt-3.5-turbo-instruct",
    "dall-e-3",
    "dall-e-2",
    "tts-1",
    "tts-1-hd",
    "whisper-1",
    "text-embedding-3-large",
    "text-embedding-3-small",
    "text-embedding-ada-002",
    "omni-moderation-latest",
    "text-moderation-latest",
    "text-moderation-stable",
    "babbage-002",
    "davinci-002",
]
